# Generated by Django 5.0.4 on 2026-04-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetWorthSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=7, unique=True)),
                ('total_net_worth', models.FloatField(default=0)),
                ('mutual_funds', models.FloatField(default=0)),
                ('retirement', models.FloatField(default=0)),
                ('liquid', models.FloatField(default=0)),
                ('emergency_fund', models.FloatField(default=0)),
                ('metals', models.FloatField(default=0)),
                ('captured_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['month'],
            },
        ),
    ]
